# Generated by Django 4.0.6 on 2022-07-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shoes',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
